USE [LibraryDB]
GO

/****** Object:  Index [PK__Discharg__CBC080073182981E]    Script Date: 1/6/2026 10:47:10 PM ******/
ALTER TABLE [dbo].[Discharge] ADD PRIMARY KEY CLUSTERED 
(
	[DischargeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [IX_BookAuthor_BookId]    Script Date: 1/6/2026 10:46:42 PM ******/
CREATE NONCLUSTERED INDEX [IX_BookAuthor_BookId] ON [dbo].[BookAuthor]
(
	[FkBookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [PK__BookAuth__21B24F59B6C1B342]    Script Date: 1/6/2026 10:47:03 PM ******/
ALTER TABLE [dbo].[BookAuthor] ADD PRIMARY KEY CLUSTERED 
(
	[BookAuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [UQ__Discharg__FE4ACA9D19EBCDCF]    Script Date: 1/6/2026 10:47:16 PM ******/
ALTER TABLE [dbo].[Discharge] ADD UNIQUE NONCLUSTERED 
(
	[FkLoanId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [PK__LibraryM__ED93FB365C0B7D40]    Script Date: 1/6/2026 10:47:27 PM ******/
ALTER TABLE [dbo].[LibraryMember] ADD PRIMARY KEY CLUSTERED 
(
	[LibraryMemberId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [UC_Member_Email]    Script Date: 1/6/2026 10:47:35 PM ******/
ALTER TABLE [dbo].[LibraryMember] ADD  CONSTRAINT [UC_Member_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [UC_Member_PersonalNumber]    Script Date: 1/6/2026 10:47:41 PM ******/
ALTER TABLE [dbo].[LibraryMember] ADD  CONSTRAINT [UC_Member_PersonalNumber] UNIQUE NONCLUSTERED 
(
	[PersonalNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [IX_Loan_BookId]    Script Date: 1/6/2026 10:47:49 PM ******/
CREATE NONCLUSTERED INDEX [IX_Loan_BookId] ON [dbo].[Loan]
(
	[FkBookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [IX_Loan_MemberId]    Script Date: 1/6/2026 10:47:53 PM ******/
CREATE NONCLUSTERED INDEX [IX_Loan_MemberId] ON [dbo].[Loan]
(
	[FkLibraryMemberId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [PK__Loan__4F5AD457232E2229]    Script Date: 1/6/2026 10:48:01 PM ******/
ALTER TABLE [dbo].[Loan] ADD PRIMARY KEY CLUSTERED 
(
	[LoanId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [IX_BookAuthor_AuthorId]    Script Date: 1/6/2026 10:46:27 PM ******/
CREATE NONCLUSTERED INDEX [IX_BookAuthor_AuthorId] ON [dbo].[BookAuthor]
(
	[FkAuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO






