USE [LibraryDB]
GO

/****** Object:  Table [dbo].[Discharge]    Script Date: 1/7/2026 8:59:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Discharge](
	[DischargeId] [int] IDENTITY(10000,1) NOT NULL,
	[FkLoanId] [int] NOT NULL,
	[DischargeDateTime] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DischargeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[FkLoanId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Discharge]  WITH CHECK ADD  CONSTRAINT [FK_LoanDischarge] FOREIGN KEY([FkLoanId])
REFERENCES [dbo].[Loan] ([LoanId])
GO

ALTER TABLE [dbo].[Discharge] CHECK CONSTRAINT [FK_LoanDischarge]
GO

